use crate::spec::{FunctionParameter, FunctionSpec};
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

const HANDWRITTEN_FUNCTIONS: &[&str] = &["SUM", "AVERAGE", "IF"];

pub fn write_spec_json(functions: &[FunctionSpec], path: &Path) -> Result<()> {
    let mut functions = functions.to_vec();

    // Mark handwritten functions as skipped
    for func in &mut functions {
        if HANDWRITTEN_FUNCTIONS.contains(&func.name.as_str()) {
            func.skipped = true;
            func.skip_reason = Some(String::from("Already implemented in handwritten.rs"));
        }
    }

    let json = serde_json::to_string_pretty(&functions)
        .context("Failed to serialize functions to JSON")?;

    fs::write(path, json).context("Failed to write spec.json")?;

    Ok(())
}

pub fn generate_functions(functions: &[FunctionSpec], path: &Path) -> Result<()> {
    let mut output = String::new();

    // File header
    output.push_str("// AUTO-GENERATED FILE - DO NOT EDIT\n");
    output.push_str("// Generated by hyperformula-codegen\n");
    output.push_str("// To regenerate: cargo run --bin hyperformula-codegen\n");
    output.push_str("\n");
    output.push_str("use hyperformula_core::{Function, FunctionContext, Value, Result, Error};\n");
    output.push_str("use std::sync::Arc;\n");
    output.push_str("use crate::FunctionRegistry;\n");
    output.push_str("\n");

    let mut generated_count = 0;
    let mut skipped_functions = Vec::new();

    // Generate struct and implementation for each function
    for func in functions {
        if HANDWRITTEN_FUNCTIONS.contains(&func.name.as_str()) {
            skipped_functions.push(func.name.clone());
            continue;
        }

        generate_function_struct(&mut output, func);
        generated_count += 1;
    }

    // Generate registration function
    output.push_str("\n");
    output.push_str("pub fn register_generated_functions(registry: &mut FunctionRegistry) {\n");

    for func in functions {
        if HANDWRITTEN_FUNCTIONS.contains(&func.name.as_str()) {
            continue;
        }
        let struct_name = to_struct_name(&func.name);
        output.push_str(&format!(
            "    registry.register(Arc::new({}));\n",
            struct_name
        ));
    }

    output.push_str("}\n");

    // Add comment about skipped functions
    if !skipped_functions.is_empty() {
        output.push_str("\n");
        output.push_str("// Skipped functions (already implemented):\n");
        for name in skipped_functions {
            output.push_str(&format!("// - {}\n", name));
        }
    }

    output.push_str(&format!(
        "\n// Generated {} function stubs\n",
        generated_count
    ));

    fs::write(path, output).context("Failed to write generated.rs")?;

    Ok(())
}

fn generate_function_struct(output: &mut String, func: &FunctionSpec) {
    let struct_name = to_struct_name(&func.name);

    // Doc comment
    if !func.description.is_empty() {
        output.push_str(&format!("/// {}\n", func.description));
    }
    output.push_str("///\n");
    output.push_str(&format!("/// **Status**: Not implemented (stub)\n"));
    output.push_str("///\n");
    output.push_str(&format!("/// **Category**: {}\n", func.category));
    if !func.url.is_empty() {
        output.push_str(&format!("/// **Documentation**: <{}>\n", func.url));
    }

    // Add signature if available
    if let Some(sig) = &func.signature {
        output.push_str("///\n");
        output.push_str(&format!("/// **Signature**: `{}`\n", sig));
    }

    // Add parameters if available
    if !func.parameters.is_empty() {
        output.push_str("///\n");
        output.push_str("/// # Parameters\n");
        for param in &func.parameters {
            let markers = parameter_markers(param);
            let marker_suffix = if markers.is_empty() {
                String::new()
            } else {
                format!(" ({})", markers.join(", "))
            };
            output.push_str(&format!(
                "/// - `{}`: {} - {}{}\n",
                param.name, param.param_type, param.description, marker_suffix
            ));
        }
    }

    output.push_str("///\n");
    output.push_str("/// # TODO\n");
    output.push_str("/// Implement this function according to the HyperFormula specification.\n");

    // Struct definition
    output.push_str(&format!("pub struct {};\n", struct_name));
    output.push_str("\n");

    // Function trait implementation
    output.push_str(&format!("impl Function for {} {{\n", struct_name));

    // name() method
    output.push_str("    fn name(&self) -> &str {\n");
    output.push_str(&format!("        \"{}\"\n", func.name));
    output.push_str("    }\n");
    output.push_str("\n");

    // aliases() method if present
    if !func.aliases.is_empty() {
        output.push_str("    fn aliases(&self) -> &[&str] {\n");
        output.push_str("        &[");
        for (i, alias) in func.aliases.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("\"{}\"", alias));
        }
        output.push_str("]\n");
        output.push_str("    }\n");
        output.push_str("\n");
    }

    // category() method
    output.push_str("    fn category(&self) -> &str {\n");
    output.push_str(&format!("        \"{}\"\n", func.category));
    output.push_str("    }\n");
    output.push_str("\n");

    // description() method
    if !func.description.is_empty() {
        output.push_str("    fn description(&self) -> &str {\n");
        let escaped_desc = func.description.replace('\\', "\\\\").replace('"', "\\\"");
        output.push_str(&format!("        \"{}\"\n", escaped_desc));
        output.push_str("    }\n");
        output.push_str("\n");
    }

    // execute() method - with parameter validation
    let args_name = if func.parameters.is_empty() {
        "_args"
    } else {
        "args"
    };
    output.push_str(&format!(
        "    fn execute(&self, {}: &[Value], _ctx: &FunctionContext) -> Result<Value> {{\n",
        args_name
    ));

    // Add parameter count validation if we have parameter info
    if !func.parameters.is_empty() {
        let arity = parameter_arity(func);

        generate_arity_validation(output, &arity);

        // Add TODO comments for parameter extraction
        output.push_str("        // TODO: Extract and validate parameters:\n");
        for (i, param) in func.parameters.iter().enumerate() {
            let markers = parameter_markers(param);
            let marker_suffix = if markers.is_empty() {
                String::new()
            } else {
                format!(" ({})", markers.join(", "))
            };
            if param.variadic {
                output.push_str(&format!(
                    "        // let {} = &args[{}..]; // {}: {}{}\n",
                    param.name, i, param.name, param.param_type, marker_suffix
                ));
            } else if param.optional {
                output.push_str(&format!(
                    "        // let {} = args.get({}); // {}: {}{}\n",
                    param.name, i, param.name, param.param_type, marker_suffix
                ));
            } else {
                output.push_str(&format!(
                    "        // let {} = &args[{}]; // {}: {}{}\n",
                    param.name, i, param.name, param.param_type, marker_suffix
                ));
            }
        }
        output.push_str("\n");
    }

    output.push_str(&format!(
        "        Err(Error::NotImplemented(\"{} function not yet implemented\".to_string()))\n",
        func.name
    ));
    output.push_str("    }\n");

    output.push_str("}\n");
    output.push_str("\n");
}

#[derive(Debug, PartialEq, Eq)]
struct FunctionArity {
    min: usize,
    max: Option<usize>,
}

fn parameter_arity(func: &FunctionSpec) -> FunctionArity {
    let min = func.parameters.iter().filter(|p| !p.optional).count();
    let max = if func.parameters.iter().any(|p| p.variadic) {
        None
    } else {
        Some(func.parameters.len())
    };

    FunctionArity { min, max }
}

fn generate_arity_validation(output: &mut String, arity: &FunctionArity) {
    match arity.max {
        None => {
            output.push_str(&format!(
                "        // Validate argument count (at least {}, variadic)\n",
                arity.min
            ));
            output.push_str(&format!("        if args.len() < {} {{\n", arity.min));
            output.push_str(&format!("            return Err(Error::InvalidArgument(format!(\"Expected at least {} arguments, got {{}}\", args.len())));\n", arity.min));
            output.push_str("        }\n");
        }
        Some(max) if arity.min == max => {
            output.push_str("        // Validate argument count\n");
            output.push_str(&format!("        if args.len() != {} {{\n", arity.min));
            output.push_str(&format!("            return Err(Error::InvalidArgument(format!(\"Expected {} arguments, got {{}}\", args.len())));\n", arity.min));
            output.push_str("        }\n");
        }
        Some(max) => {
            output.push_str(&format!(
                "        // Validate argument count ({} required, {} optional)\n",
                arity.min,
                max - arity.min
            ));
            output.push_str(&format!(
                "        if args.len() < {} || args.len() > {} {{\n",
                arity.min, max
            ));
            output.push_str(&format!("            return Err(Error::InvalidArgument(format!(\"Expected {}-{} arguments, got {{}}\", args.len())));\n", arity.min, max));
            output.push_str("        }\n");
        }
    }
    output.push_str("\n");
}

fn parameter_markers(param: &FunctionParameter) -> Vec<&'static str> {
    let mut markers = Vec::new();
    if param.optional {
        markers.push("optional");
    }
    if param.variadic {
        markers.push("variadic");
    }
    markers
}

pub fn generate_tests(functions: &[FunctionSpec], path: &Path) -> Result<()> {
    let mut output = String::new();

    // File header
    output.push_str("// AUTO-GENERATED FILE - DO NOT EDIT\n");
    output.push_str("// Generated by hyperformula-codegen\n");
    output.push_str("// To regenerate: cargo run --bin hyperformula-codegen\n");
    output.push_str("\n");
    output.push_str("use hyperformula_core::FunctionContext;\n");
    output.push_str("use hyperformula_funcs::FunctionRegistry;\n");
    output.push_str("\n");

    let mut generated_count = 0;

    // Generate test for each function
    for func in functions {
        if HANDWRITTEN_FUNCTIONS.contains(&func.name.as_str()) {
            continue;
        }

        generate_test_function(&mut output, func);
        generated_count += 1;
    }

    output.push_str(&format!(
        "\n// Generated {} test stubs (all marked #[ignore])\n",
        generated_count
    ));

    fs::write(path, output).context("Failed to write generated_tests.rs")?;

    Ok(())
}

fn generate_test_function(output: &mut String, func: &FunctionSpec) {
    let test_name = format!("test_generated_{}", func.name.to_lowercase());

    // Doc comment
    output.push_str(&format!("/// Test for {} function\n", func.name));
    output.push_str("///\n");
    output.push_str("/// # TODO\n");
    output.push_str("/// Implement test cases according to the HyperFormula specification.\n");
    if !func.url.is_empty() {
        output.push_str(&format!("/// Documentation: <{}>\n", func.url));
    }

    // Test attributes
    output.push_str("#[test]\n");
    output.push_str("#[ignore] // Remove this attribute when implementing the function\n");
    output.push_str(&format!("fn {}() {{\n", test_name));

    // Test body
    output.push_str("    let registry = FunctionRegistry::new();\n");
    output.push_str(&format!(
        "    let func = registry.get(\"{}\").expect(\"Function should be registered\");\n",
        func.name
    ));
    output.push_str("    let _ctx = FunctionContext::new();\n");
    output.push_str("\n");
    output.push_str("    // TODO: Add test cases\n");
    output.push_str("    // Example:\n");
    output.push_str("    // let args = vec![hyperformula_core::Value::Number(1.0), hyperformula_core::Value::Number(2.0)];\n");
    output.push_str("    // let result = func.execute(&args, &_ctx);\n");
    output.push_str("    // assert!(matches!(result, Ok(hyperformula_core::Value::Number(_))));\n");
    output.push_str("\n");
    output.push_str("    // For now, just verify the function is registered\n");
    output.push_str(&format!(
        "    assert_eq!(func.name(), \"{}\");\n",
        func.name
    ));

    output.push_str("}\n");
    output.push_str("\n");
}

fn to_struct_name(function_name: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;

    for c in function_name.chars() {
        if c.is_alphanumeric() {
            if capitalize_next {
                result.push_str(&c.to_uppercase().to_string());
                capitalize_next = false;
            } else {
                result.push_str(&c.to_lowercase().to_string());
            }
        } else {
            capitalize_next = true;
        }
    }

    result.push_str("Function");
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_struct_name() {
        assert_eq!(to_struct_name("SUM"), "SumFunction");
        assert_eq!(to_struct_name("AVERAGE"), "AverageFunction");
        assert_eq!(to_struct_name("VLOOKUP"), "VlookupFunction");
        assert_eq!(to_struct_name("IF"), "IfFunction");
    }

    #[test]
    fn test_parameter_arity_with_optional_argument() {
        let mut func = FunctionSpec::new("VLOOKUP".to_string());
        func.parameters = vec![
            test_param("lookup_value", false, false),
            test_param("table_array", false, false),
            test_param("col_index_num", false, false),
            test_param("range_lookup", true, false),
        ];

        assert_eq!(
            parameter_arity(&func),
            FunctionArity {
                min: 3,
                max: Some(4)
            }
        );
    }

    #[test]
    fn test_parameter_arity_with_variadic_argument() {
        let mut func = FunctionSpec::new("CHOOSE".to_string());
        func.parameters = vec![
            test_param("index_num", false, false),
            test_param("values", false, true),
        ];

        assert_eq!(parameter_arity(&func), FunctionArity { min: 2, max: None });
    }

    fn test_param(name: &str, optional: bool, variadic: bool) -> FunctionParameter {
        FunctionParameter {
            name: name.to_string(),
            param_type: "Any".to_string(),
            optional,
            variadic,
            description: String::new(),
        }
    }
}
