// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by hyperformula-codegen
// To regenerate: cargo run --bin hyperformula-codegen

use hyperformula_core::{Function, FunctionContext, Value, Result, Error};
use std::sync::Arc;
use crate::FunctionRegistry;

/// Returns the absolute value of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AbsFunction;

impl Function for AbsFunction {
    fn name(&self) -> &str {
        "ABS"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the absolute value of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ABS function not yet implemented".to_string()))
    }
}

/// Returns the arccosine of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AcosFunction;

impl Function for AcosFunction {
    fn name(&self) -> &str {
        "ACOS"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the arccosine of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ACOS function not yet implemented".to_string()))
    }
}

/// Returns the inverse hyperbolic cosine of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AcoshFunction;

impl Function for AcoshFunction {
    fn name(&self) -> &str {
        "ACOSH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the inverse hyperbolic cosine of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ACOSH function not yet implemented".to_string()))
    }
}

/// Returns the arccotangent of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AcotFunction;

impl Function for AcotFunction {
    fn name(&self) -> &str {
        "ACOT"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the arccotangent of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ACOT function not yet implemented".to_string()))
    }
}

/// Returns the hyperbolic arccotangent of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AcothFunction;

impl Function for AcothFunction {
    fn name(&self) -> &str {
        "ACOTH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the hyperbolic arccotangent of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ACOTH function not yet implemented".to_string()))
    }
}

/// Returns TRUE if all arguments are TRUE
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AndFunction;

impl Function for AndFunction {
    fn name(&self) -> &str {
        "AND"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns TRUE if all arguments are TRUE"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("AND function not yet implemented".to_string()))
    }
}

/// Returns the arcsine of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AsinFunction;

impl Function for AsinFunction {
    fn name(&self) -> &str {
        "ASIN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the arcsine of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ASIN function not yet implemented".to_string()))
    }
}

/// Returns the inverse hyperbolic sine of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AsinhFunction;

impl Function for AsinhFunction {
    fn name(&self) -> &str {
        "ASINH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the inverse hyperbolic sine of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ASINH function not yet implemented".to_string()))
    }
}

/// Returns the arctangent of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AtanFunction;

impl Function for AtanFunction {
    fn name(&self) -> &str {
        "ATAN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the arctangent of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ATAN function not yet implemented".to_string()))
    }
}

/// Returns the arctangent from x and y coordinates
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct Atan2Function;

impl Function for Atan2Function {
    fn name(&self) -> &str {
        "ATAN2"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the arctangent from x and y coordinates"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ATAN2 function not yet implemented".to_string()))
    }
}

/// Returns the inverse hyperbolic tangent of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct AtanhFunction;

impl Function for AtanhFunction {
    fn name(&self) -> &str {
        "ATANH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the inverse hyperbolic tangent of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ATANH function not yet implemented".to_string()))
    }
}

/// Rounds a number up to the nearest integer or multiple
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CeilingFunction;

impl Function for CeilingFunction {
    fn name(&self) -> &str {
        "CEILING"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number up to the nearest integer or multiple"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("CEILING function not yet implemented".to_string()))
    }
}

/// Chooses a value from a list of values
///
/// **Status**: Implemented
///
/// **Category**: Lookup
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// **Signature**: `CHOOSE(index_num, value1, [value2], ...)`
///
/// # Parameters
/// - `index_num`: Number - Specifies which value argument to select (1-based)
/// - `values`: Any - One or more values to choose from (variadic)
///
pub struct ChooseFunction;

impl Function for ChooseFunction {
    fn name(&self) -> &str {
        "CHOOSE"
    }

    fn category(&self) -> &str {
        "Lookup"
    }

    fn description(&self) -> &str {
        "Chooses a value from a list of values"
    }

    fn execute(&self, args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        if args.len() < 2 {
            return Err(Error::InvalidArgument(format!(
                "Expected at least 2 arguments, got {}",
                args.len()
            )));
        }

        let index_num = match args[0].as_number() {
            Some(n) => n,
            None => return Err(Error::ValueError("Index must be a number".to_string())),
        };

        if !index_num.is_finite() || index_num < 1.0 {
            return Err(Error::ValueError("Index must be at least 1".to_string()));
        }

        let values = &args[1..];
        let index = index_num.trunc();

        if index > values.len() as f64 {
            return Err(Error::ValueError(format!(
                "Index {} is out of bounds (1-{})",
                index,
                values.len()
            )));
        }

        Ok(values[index as usize - 1].clone())
    }
}

/// Combines text from multiple ranges
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ConcatFunction;

impl Function for ConcatFunction {
    fn name(&self) -> &str {
        "CONCAT"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Combines text from multiple ranges"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("CONCAT function not yet implemented".to_string()))
    }
}

/// Joins several text strings into one string
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ConcatenateFunction;

impl Function for ConcatenateFunction {
    fn name(&self) -> &str {
        "CONCATENATE"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Joins several text strings into one string"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("CONCATENATE function not yet implemented".to_string()))
    }
}

/// Returns the cosine of an angle
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CosFunction;

impl Function for CosFunction {
    fn name(&self) -> &str {
        "COS"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the cosine of an angle"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COS function not yet implemented".to_string()))
    }
}

/// Returns the hyperbolic cosine of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CoshFunction;

impl Function for CoshFunction {
    fn name(&self) -> &str {
        "COSH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the hyperbolic cosine of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COSH function not yet implemented".to_string()))
    }
}

/// Returns the cotangent of an angle
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CotFunction;

impl Function for CotFunction {
    fn name(&self) -> &str {
        "COT"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the cotangent of an angle"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COT function not yet implemented".to_string()))
    }
}

/// Returns the hyperbolic cotangent of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CothFunction;

impl Function for CothFunction {
    fn name(&self) -> &str {
        "COTH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the hyperbolic cotangent of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COTH function not yet implemented".to_string()))
    }
}

/// Counts the number of cells that contain numbers
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CountFunction;

impl Function for CountFunction {
    fn name(&self) -> &str {
        "COUNT"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Counts the number of cells that contain numbers"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COUNT function not yet implemented".to_string()))
    }
}

/// Counts the number of non-empty cells
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CountaFunction;

impl Function for CountaFunction {
    fn name(&self) -> &str {
        "COUNTA"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Counts the number of non-empty cells"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COUNTA function not yet implemented".to_string()))
    }
}

/// Counts the number of blank cells
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct CountblankFunction;

impl Function for CountblankFunction {
    fn name(&self) -> &str {
        "COUNTBLANK"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Counts the number of blank cells"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("COUNTBLANK function not yet implemented".to_string()))
    }
}

/// Returns the serial number of a particular date
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct DateFunction;

impl Function for DateFunction {
    fn name(&self) -> &str {
        "DATE"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the serial number of a particular date"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("DATE function not yet implemented".to_string()))
    }
}

/// Converts a date in text format to a serial number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct DatevalueFunction;

impl Function for DatevalueFunction {
    fn name(&self) -> &str {
        "DATEVALUE"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Converts a date in text format to a serial number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("DATEVALUE function not yet implemented".to_string()))
    }
}

/// Returns the day of a date
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct DayFunction;

impl Function for DayFunction {
    fn name(&self) -> &str {
        "DAY"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the day of a date"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("DAY function not yet implemented".to_string()))
    }
}

/// Converts radians to degrees
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct DegreesFunction;

impl Function for DegreesFunction {
    fn name(&self) -> &str {
        "DEGREES"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Converts radians to degrees"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("DEGREES function not yet implemented".to_string()))
    }
}

/// Rounds a number up to the nearest even integer
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct EvenFunction;

impl Function for EvenFunction {
    fn name(&self) -> &str {
        "EVEN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number up to the nearest even integer"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("EVEN function not yet implemented".to_string()))
    }
}

/// Returns e raised to the power of a given number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ExpFunction;

impl Function for ExpFunction {
    fn name(&self) -> &str {
        "EXP"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns e raised to the power of a given number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("EXP function not yet implemented".to_string()))
    }
}

/// Returns the factorial of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct FactFunction;

impl Function for FactFunction {
    fn name(&self) -> &str {
        "FACT"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the factorial of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("FACT function not yet implemented".to_string()))
    }
}

/// Returns the logical value FALSE
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct FalseFunction;

impl Function for FalseFunction {
    fn name(&self) -> &str {
        "FALSE"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns the logical value FALSE"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("FALSE function not yet implemented".to_string()))
    }
}

/// Finds one text value within another (case-sensitive)
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct FindFunction;

impl Function for FindFunction {
    fn name(&self) -> &str {
        "FIND"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Finds one text value within another (case-sensitive)"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("FIND function not yet implemented".to_string()))
    }
}

/// Rounds a number down to the nearest integer or multiple
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct FloorFunction;

impl Function for FloorFunction {
    fn name(&self) -> &str {
        "FLOOR"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number down to the nearest integer or multiple"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("FLOOR function not yet implemented".to_string()))
    }
}

/// Looks up a value in the first row and returns a value in the same column
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Lookup
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// **Signature**: `HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])`
///
/// # Parameters
/// - `lookup_value`: Any - The value to search for in the first row of the table
/// - `table_array`: Range - The table of data to search. Must be at least 2 rows tall
/// - `row_index_num`: Number - The row number in the table from which to return a value (1-based)
/// - `range_lookup`: Boolean - Optional. TRUE for approximate match (default), FALSE for exact match (optional)
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct HlookupFunction;

impl Function for HlookupFunction {
    fn name(&self) -> &str {
        "HLOOKUP"
    }

    fn category(&self) -> &str {
        "Lookup"
    }

    fn description(&self) -> &str {
        "Looks up a value in the first row and returns a value in the same column"
    }

    fn execute(&self, args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        // Validate argument count (3 required, 1 optional)
        if args.len() < 3 || args.len() > 4 {
            return Err(Error::InvalidArgument(format!("Expected 3-4 arguments, got {}", args.len())));
        }

        // TODO: Extract and validate parameters:
        // let lookup_value = &args[0]; // lookup_value: Any
        // let table_array = &args[1]; // table_array: Range
        // let row_index_num = &args[2]; // row_index_num: Number
        // let range_lookup = args.get(3); // range_lookup: Boolean (optional)

        Err(Error::NotImplemented("HLOOKUP function not yet implemented".to_string()))
    }
}

/// Returns the hour of a time value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct HourFunction;

impl Function for HourFunction {
    fn name(&self) -> &str {
        "HOUR"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the hour of a time value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("HOUR function not yet implemented".to_string()))
    }
}

/// Returns a value if an expression results in an error
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IferrorFunction;

impl Function for IferrorFunction {
    fn name(&self) -> &str {
        "IFERROR"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns a value if an expression results in an error"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("IFERROR function not yet implemented".to_string()))
    }
}

/// Returns a value if an expression results in #N/A
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IfnaFunction;

impl Function for IfnaFunction {
    fn name(&self) -> &str {
        "IFNA"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns a value if an expression results in #N/A"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("IFNA function not yet implemented".to_string()))
    }
}

/// Returns a value from a table based on row and column numbers
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Lookup
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// **Signature**: `INDEX(array, row_num, [column_num])`
///
/// # Parameters
/// - `array`: Range - The range of cells or array from which to return a value
/// - `row_num`: Number - The row number in the array from which to return a value (1-based)
/// - `column_num`: Number - Optional. The column number in the array from which to return a value (1-based) (optional)
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IndexFunction;

impl Function for IndexFunction {
    fn name(&self) -> &str {
        "INDEX"
    }

    fn category(&self) -> &str {
        "Lookup"
    }

    fn description(&self) -> &str {
        "Returns a value from a table based on row and column numbers"
    }

    fn execute(&self, args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        // Validate argument count (2 required, 1 optional)
        if args.len() < 2 || args.len() > 3 {
            return Err(Error::InvalidArgument(format!("Expected 2-3 arguments, got {}", args.len())));
        }

        // TODO: Extract and validate parameters:
        // let array = &args[0]; // array: Range
        // let row_num = &args[1]; // row_num: Number
        // let column_num = args.get(2); // column_num: Number (optional)

        Err(Error::NotImplemented("INDEX function not yet implemented".to_string()))
    }
}

/// Rounds a number down to the nearest integer
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IntFunction;

impl Function for IntFunction {
    fn name(&self) -> &str {
        "INT"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number down to the nearest integer"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("INT function not yet implemented".to_string()))
    }
}

/// Returns TRUE if the value is blank
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IsblankFunction;

impl Function for IsblankFunction {
    fn name(&self) -> &str {
        "ISBLANK"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns TRUE if the value is blank"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ISBLANK function not yet implemented".to_string()))
    }
}

/// Returns TRUE if the value is any error
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IserrorFunction;

impl Function for IserrorFunction {
    fn name(&self) -> &str {
        "ISERROR"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns TRUE if the value is any error"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ISERROR function not yet implemented".to_string()))
    }
}

/// Returns TRUE if the value is a logical value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IslogicalFunction;

impl Function for IslogicalFunction {
    fn name(&self) -> &str {
        "ISLOGICAL"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns TRUE if the value is a logical value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ISLOGICAL function not yet implemented".to_string()))
    }
}

/// Returns TRUE if the value is #N/A
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IsnaFunction;

impl Function for IsnaFunction {
    fn name(&self) -> &str {
        "ISNA"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns TRUE if the value is #N/A"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ISNA function not yet implemented".to_string()))
    }
}

/// Returns TRUE if the value is a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IsnumberFunction;

impl Function for IsnumberFunction {
    fn name(&self) -> &str {
        "ISNUMBER"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns TRUE if the value is a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ISNUMBER function not yet implemented".to_string()))
    }
}

/// Returns TRUE if the value is text
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct IstextFunction;

impl Function for IstextFunction {
    fn name(&self) -> &str {
        "ISTEXT"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns TRUE if the value is text"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ISTEXT function not yet implemented".to_string()))
    }
}

/// Returns the leftmost characters from a text value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct LeftFunction;

impl Function for LeftFunction {
    fn name(&self) -> &str {
        "LEFT"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Returns the leftmost characters from a text value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("LEFT function not yet implemented".to_string()))
    }
}

/// Returns the length of a string
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct LenFunction;

impl Function for LenFunction {
    fn name(&self) -> &str {
        "LEN"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Returns the length of a string"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("LEN function not yet implemented".to_string()))
    }
}

/// Returns the natural logarithm of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct LnFunction;

impl Function for LnFunction {
    fn name(&self) -> &str {
        "LN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the natural logarithm of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("LN function not yet implemented".to_string()))
    }
}

/// Returns the logarithm of a number to a specified base
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct LogFunction;

impl Function for LogFunction {
    fn name(&self) -> &str {
        "LOG"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the logarithm of a number to a specified base"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("LOG function not yet implemented".to_string()))
    }
}

/// Returns the base-10 logarithm of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct Log10Function;

impl Function for Log10Function {
    fn name(&self) -> &str {
        "LOG10"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the base-10 logarithm of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("LOG10 function not yet implemented".to_string()))
    }
}

/// Converts text to lowercase
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct LowerFunction;

impl Function for LowerFunction {
    fn name(&self) -> &str {
        "LOWER"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Converts text to lowercase"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("LOWER function not yet implemented".to_string()))
    }
}

/// Returns the relative position of an item in an array
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Lookup
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// **Signature**: `MATCH(lookup_value, lookup_array, [match_type])`
///
/// # Parameters
/// - `lookup_value`: Any - The value to search for in the array
/// - `lookup_array`: Range - The range of cells to search
/// - `match_type`: Number - Optional. 1 (default) = largest value <= lookup_value, 0 = exact match, -1 = smallest value >= lookup_value (optional)
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MatchFunction;

impl Function for MatchFunction {
    fn name(&self) -> &str {
        "MATCH"
    }

    fn category(&self) -> &str {
        "Lookup"
    }

    fn description(&self) -> &str {
        "Returns the relative position of an item in an array"
    }

    fn execute(&self, args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        // Validate argument count (2 required, 1 optional)
        if args.len() < 2 || args.len() > 3 {
            return Err(Error::InvalidArgument(format!("Expected 2-3 arguments, got {}", args.len())));
        }

        // TODO: Extract and validate parameters:
        // let lookup_value = &args[0]; // lookup_value: Any
        // let lookup_array = &args[1]; // lookup_array: Range
        // let match_type = args.get(2); // match_type: Number (optional)

        Err(Error::NotImplemented("MATCH function not yet implemented".to_string()))
    }
}

/// Returns the maximum value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MaxFunction;

impl Function for MaxFunction {
    fn name(&self) -> &str {
        "MAX"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Returns the maximum value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MAX function not yet implemented".to_string()))
    }
}

/// Returns the maximum value, including text and logical values
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MaxaFunction;

impl Function for MaxaFunction {
    fn name(&self) -> &str {
        "MAXA"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Returns the maximum value, including text and logical values"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MAXA function not yet implemented".to_string()))
    }
}

/// Returns the median of a set of numbers
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MedianFunction;

impl Function for MedianFunction {
    fn name(&self) -> &str {
        "MEDIAN"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Returns the median of a set of numbers"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MEDIAN function not yet implemented".to_string()))
    }
}

/// Returns a specific number of characters from a text string
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MidFunction;

impl Function for MidFunction {
    fn name(&self) -> &str {
        "MID"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Returns a specific number of characters from a text string"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MID function not yet implemented".to_string()))
    }
}

/// Returns the minimum value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MinFunction;

impl Function for MinFunction {
    fn name(&self) -> &str {
        "MIN"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Returns the minimum value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MIN function not yet implemented".to_string()))
    }
}

/// Returns the minimum value, including text and logical values
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MinaFunction;

impl Function for MinaFunction {
    fn name(&self) -> &str {
        "MINA"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Returns the minimum value, including text and logical values"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MINA function not yet implemented".to_string()))
    }
}

/// Returns the minute of a time value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MinuteFunction;

impl Function for MinuteFunction {
    fn name(&self) -> &str {
        "MINUTE"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the minute of a time value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MINUTE function not yet implemented".to_string()))
    }
}

/// Returns the remainder from division
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ModFunction;

impl Function for ModFunction {
    fn name(&self) -> &str {
        "MOD"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the remainder from division"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MOD function not yet implemented".to_string()))
    }
}

/// Returns the most common value in a dataset
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ModeFunction;

impl Function for ModeFunction {
    fn name(&self) -> &str {
        "MODE"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Returns the most common value in a dataset"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MODE function not yet implemented".to_string()))
    }
}

/// Returns the month of a date
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct MonthFunction;

impl Function for MonthFunction {
    fn name(&self) -> &str {
        "MONTH"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the month of a date"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("MONTH function not yet implemented".to_string()))
    }
}

/// Converts a value to a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct NFunction;

impl Function for NFunction {
    fn name(&self) -> &str {
        "N"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Converts a value to a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("N function not yet implemented".to_string()))
    }
}

/// Reverses the logic of its argument
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct NotFunction;

impl Function for NotFunction {
    fn name(&self) -> &str {
        "NOT"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Reverses the logic of its argument"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("NOT function not yet implemented".to_string()))
    }
}

/// Returns the current date and time
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct NowFunction;

impl Function for NowFunction {
    fn name(&self) -> &str {
        "NOW"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the current date and time"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("NOW function not yet implemented".to_string()))
    }
}

/// Rounds a number up to the nearest odd integer
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct OddFunction;

impl Function for OddFunction {
    fn name(&self) -> &str {
        "ODD"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number up to the nearest odd integer"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ODD function not yet implemented".to_string()))
    }
}

/// Returns TRUE if any argument is TRUE
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct OrFunction;

impl Function for OrFunction {
    fn name(&self) -> &str {
        "OR"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns TRUE if any argument is TRUE"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("OR function not yet implemented".to_string()))
    }
}

/// Returns the value of pi
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct PiFunction;

impl Function for PiFunction {
    fn name(&self) -> &str {
        "PI"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the value of pi"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("PI function not yet implemented".to_string()))
    }
}

/// Returns the result of a number raised to a power
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct PowerFunction;

impl Function for PowerFunction {
    fn name(&self) -> &str {
        "POWER"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the result of a number raised to a power"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("POWER function not yet implemented".to_string()))
    }
}

/// Capitalizes the first letter of each word
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ProperFunction;

impl Function for ProperFunction {
    fn name(&self) -> &str {
        "PROPER"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Capitalizes the first letter of each word"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("PROPER function not yet implemented".to_string()))
    }
}

/// Converts degrees to radians
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RadiansFunction;

impl Function for RadiansFunction {
    fn name(&self) -> &str {
        "RADIANS"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Converts degrees to radians"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("RADIANS function not yet implemented".to_string()))
    }
}

/// Returns a random number between 0 and 1
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RandFunction;

impl Function for RandFunction {
    fn name(&self) -> &str {
        "RAND"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns a random number between 0 and 1"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("RAND function not yet implemented".to_string()))
    }
}

/// Returns a random integer between two values
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RandbetweenFunction;

impl Function for RandbetweenFunction {
    fn name(&self) -> &str {
        "RANDBETWEEN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns a random integer between two values"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("RANDBETWEEN function not yet implemented".to_string()))
    }
}

/// Replaces part of a text string
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ReplaceFunction;

impl Function for ReplaceFunction {
    fn name(&self) -> &str {
        "REPLACE"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Replaces part of a text string"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("REPLACE function not yet implemented".to_string()))
    }
}

/// Returns the rightmost characters from a text value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RightFunction;

impl Function for RightFunction {
    fn name(&self) -> &str {
        "RIGHT"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Returns the rightmost characters from a text value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("RIGHT function not yet implemented".to_string()))
    }
}

/// Rounds a number to a specified number of digits
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RoundFunction;

impl Function for RoundFunction {
    fn name(&self) -> &str {
        "ROUND"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number to a specified number of digits"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ROUND function not yet implemented".to_string()))
    }
}

/// Rounds a number down
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RounddownFunction;

impl Function for RounddownFunction {
    fn name(&self) -> &str {
        "ROUNDDOWN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number down"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ROUNDDOWN function not yet implemented".to_string()))
    }
}

/// Rounds a number up
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct RoundupFunction;

impl Function for RoundupFunction {
    fn name(&self) -> &str {
        "ROUNDUP"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Rounds a number up"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("ROUNDUP function not yet implemented".to_string()))
    }
}

/// Finds one text value within another (case-insensitive)
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SearchFunction;

impl Function for SearchFunction {
    fn name(&self) -> &str {
        "SEARCH"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Finds one text value within another (case-insensitive)"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SEARCH function not yet implemented".to_string()))
    }
}

/// Returns the second of a time value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SecondFunction;

impl Function for SecondFunction {
    fn name(&self) -> &str {
        "SECOND"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the second of a time value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SECOND function not yet implemented".to_string()))
    }
}

/// Returns the sign of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SignFunction;

impl Function for SignFunction {
    fn name(&self) -> &str {
        "SIGN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the sign of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SIGN function not yet implemented".to_string()))
    }
}

/// Returns the sine of an angle
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SinFunction;

impl Function for SinFunction {
    fn name(&self) -> &str {
        "SIN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the sine of an angle"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SIN function not yet implemented".to_string()))
    }
}

/// Returns the hyperbolic sine of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SinhFunction;

impl Function for SinhFunction {
    fn name(&self) -> &str {
        "SINH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the hyperbolic sine of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SINH function not yet implemented".to_string()))
    }
}

/// Returns the square root of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SqrtFunction;

impl Function for SqrtFunction {
    fn name(&self) -> &str {
        "SQRT"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the square root of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SQRT function not yet implemented".to_string()))
    }
}

/// Estimates standard deviation based on a sample
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct StdevFunction;

impl Function for StdevFunction {
    fn name(&self) -> &str {
        "STDEV"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Estimates standard deviation based on a sample"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("STDEV function not yet implemented".to_string()))
    }
}

/// Calculates standard deviation based on entire population
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct StdevpFunction;

impl Function for StdevpFunction {
    fn name(&self) -> &str {
        "STDEVP"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Calculates standard deviation based on entire population"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("STDEVP function not yet implemented".to_string()))
    }
}

/// Substitutes new text for old text in a string
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct SubstituteFunction;

impl Function for SubstituteFunction {
    fn name(&self) -> &str {
        "SUBSTITUTE"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Substitutes new text for old text in a string"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("SUBSTITUTE function not yet implemented".to_string()))
    }
}

/// Returns the tangent of an angle
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TanFunction;

impl Function for TanFunction {
    fn name(&self) -> &str {
        "TAN"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the tangent of an angle"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TAN function not yet implemented".to_string()))
    }
}

/// Returns the hyperbolic tangent of a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TanhFunction;

impl Function for TanhFunction {
    fn name(&self) -> &str {
        "TANH"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Returns the hyperbolic tangent of a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TANH function not yet implemented".to_string()))
    }
}

/// Formats a number and converts it to text
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TextFunction;

impl Function for TextFunction {
    fn name(&self) -> &str {
        "TEXT"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Formats a number and converts it to text"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TEXT function not yet implemented".to_string()))
    }
}

/// Returns the serial number of a particular time
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TimeFunction;

impl Function for TimeFunction {
    fn name(&self) -> &str {
        "TIME"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the serial number of a particular time"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TIME function not yet implemented".to_string()))
    }
}

/// Converts a time in text format to a serial number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TimevalueFunction;

impl Function for TimevalueFunction {
    fn name(&self) -> &str {
        "TIMEVALUE"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Converts a time in text format to a serial number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TIMEVALUE function not yet implemented".to_string()))
    }
}

/// Returns the current date
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TodayFunction;

impl Function for TodayFunction {
    fn name(&self) -> &str {
        "TODAY"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the current date"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TODAY function not yet implemented".to_string()))
    }
}

/// Removes extra spaces from text
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TrimFunction;

impl Function for TrimFunction {
    fn name(&self) -> &str {
        "TRIM"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Removes extra spaces from text"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TRIM function not yet implemented".to_string()))
    }
}

/// Returns the logical value TRUE
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TrueFunction;

impl Function for TrueFunction {
    fn name(&self) -> &str {
        "TRUE"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns the logical value TRUE"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TRUE function not yet implemented".to_string()))
    }
}

/// Truncates a number to an integer
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Math
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TruncFunction;

impl Function for TruncFunction {
    fn name(&self) -> &str {
        "TRUNC"
    }

    fn category(&self) -> &str {
        "Math"
    }

    fn description(&self) -> &str {
        "Truncates a number to an integer"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TRUNC function not yet implemented".to_string()))
    }
}

/// Returns a number indicating the data type of a value
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Information
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct TypeFunction;

impl Function for TypeFunction {
    fn name(&self) -> &str {
        "TYPE"
    }

    fn category(&self) -> &str {
        "Information"
    }

    fn description(&self) -> &str {
        "Returns a number indicating the data type of a value"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("TYPE function not yet implemented".to_string()))
    }
}

/// Converts text to uppercase
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct UpperFunction;

impl Function for UpperFunction {
    fn name(&self) -> &str {
        "UPPER"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Converts text to uppercase"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("UPPER function not yet implemented".to_string()))
    }
}

/// Converts a text string that represents a number to a number
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Text
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct ValueFunction;

impl Function for ValueFunction {
    fn name(&self) -> &str {
        "VALUE"
    }

    fn category(&self) -> &str {
        "Text"
    }

    fn description(&self) -> &str {
        "Converts a text string that represents a number to a number"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("VALUE function not yet implemented".to_string()))
    }
}

/// Estimates variance based on a sample
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct VarFunction;

impl Function for VarFunction {
    fn name(&self) -> &str {
        "VAR"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Estimates variance based on a sample"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("VAR function not yet implemented".to_string()))
    }
}

/// Calculates variance based on entire population
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Statistical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct VarpFunction;

impl Function for VarpFunction {
    fn name(&self) -> &str {
        "VARP"
    }

    fn category(&self) -> &str {
        "Statistical"
    }

    fn description(&self) -> &str {
        "Calculates variance based on entire population"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("VARP function not yet implemented".to_string()))
    }
}

/// Looks up a value in the first column and returns a value in the same row
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Lookup
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// **Signature**: `VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])`
///
/// # Parameters
/// - `lookup_value`: Any - The value to search for in the first column of the table
/// - `table_array`: Range - The table of data to search. Must be at least 2 columns wide
/// - `col_index_num`: Number - The column number in the table from which to return a value (1-based)
/// - `range_lookup`: Boolean - Optional. TRUE for approximate match (default), FALSE for exact match (optional)
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct VlookupFunction;

impl Function for VlookupFunction {
    fn name(&self) -> &str {
        "VLOOKUP"
    }

    fn category(&self) -> &str {
        "Lookup"
    }

    fn description(&self) -> &str {
        "Looks up a value in the first column and returns a value in the same row"
    }

    fn execute(&self, args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        // Validate argument count (3 required, 1 optional)
        if args.len() < 3 || args.len() > 4 {
            return Err(Error::InvalidArgument(format!("Expected 3-4 arguments, got {}", args.len())));
        }

        // TODO: Extract and validate parameters:
        // let lookup_value = &args[0]; // lookup_value: Any
        // let table_array = &args[1]; // table_array: Range
        // let col_index_num = &args[2]; // col_index_num: Number
        // let range_lookup = args.get(3); // range_lookup: Boolean (optional)

        Err(Error::NotImplemented("VLOOKUP function not yet implemented".to_string()))
    }
}

/// Returns a logical exclusive OR of all arguments
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Logical
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct XorFunction;

impl Function for XorFunction {
    fn name(&self) -> &str {
        "XOR"
    }

    fn category(&self) -> &str {
        "Logical"
    }

    fn description(&self) -> &str {
        "Returns a logical exclusive OR of all arguments"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("XOR function not yet implemented".to_string()))
    }
}

/// Returns the year of a date
///
/// **Status**: Not implemented (stub)
///
/// **Category**: Date
/// **Documentation**: <https://hyperformula.handsontable.com/guide/built-in-functions.html>
///
/// # TODO
/// Implement this function according to the HyperFormula specification.
pub struct YearFunction;

impl Function for YearFunction {
    fn name(&self) -> &str {
        "YEAR"
    }

    fn category(&self) -> &str {
        "Date"
    }

    fn description(&self) -> &str {
        "Returns the year of a date"
    }

    fn execute(&self, _args: &[Value], _ctx: &FunctionContext) -> Result<Value> {
        Err(Error::NotImplemented("YEAR function not yet implemented".to_string()))
    }
}


pub fn register_generated_functions(registry: &mut FunctionRegistry) {
    registry.register(Arc::new(AbsFunction));
    registry.register(Arc::new(AcosFunction));
    registry.register(Arc::new(AcoshFunction));
    registry.register(Arc::new(AcotFunction));
    registry.register(Arc::new(AcothFunction));
    registry.register(Arc::new(AndFunction));
    registry.register(Arc::new(AsinFunction));
    registry.register(Arc::new(AsinhFunction));
    registry.register(Arc::new(AtanFunction));
    registry.register(Arc::new(Atan2Function));
    registry.register(Arc::new(AtanhFunction));
    registry.register(Arc::new(CeilingFunction));
    registry.register(Arc::new(ChooseFunction));
    registry.register(Arc::new(ConcatFunction));
    registry.register(Arc::new(ConcatenateFunction));
    registry.register(Arc::new(CosFunction));
    registry.register(Arc::new(CoshFunction));
    registry.register(Arc::new(CotFunction));
    registry.register(Arc::new(CothFunction));
    registry.register(Arc::new(CountFunction));
    registry.register(Arc::new(CountaFunction));
    registry.register(Arc::new(CountblankFunction));
    registry.register(Arc::new(DateFunction));
    registry.register(Arc::new(DatevalueFunction));
    registry.register(Arc::new(DayFunction));
    registry.register(Arc::new(DegreesFunction));
    registry.register(Arc::new(EvenFunction));
    registry.register(Arc::new(ExpFunction));
    registry.register(Arc::new(FactFunction));
    registry.register(Arc::new(FalseFunction));
    registry.register(Arc::new(FindFunction));
    registry.register(Arc::new(FloorFunction));
    registry.register(Arc::new(HlookupFunction));
    registry.register(Arc::new(HourFunction));
    registry.register(Arc::new(IferrorFunction));
    registry.register(Arc::new(IfnaFunction));
    registry.register(Arc::new(IndexFunction));
    registry.register(Arc::new(IntFunction));
    registry.register(Arc::new(IsblankFunction));
    registry.register(Arc::new(IserrorFunction));
    registry.register(Arc::new(IslogicalFunction));
    registry.register(Arc::new(IsnaFunction));
    registry.register(Arc::new(IsnumberFunction));
    registry.register(Arc::new(IstextFunction));
    registry.register(Arc::new(LeftFunction));
    registry.register(Arc::new(LenFunction));
    registry.register(Arc::new(LnFunction));
    registry.register(Arc::new(LogFunction));
    registry.register(Arc::new(Log10Function));
    registry.register(Arc::new(LowerFunction));
    registry.register(Arc::new(MatchFunction));
    registry.register(Arc::new(MaxFunction));
    registry.register(Arc::new(MaxaFunction));
    registry.register(Arc::new(MedianFunction));
    registry.register(Arc::new(MidFunction));
    registry.register(Arc::new(MinFunction));
    registry.register(Arc::new(MinaFunction));
    registry.register(Arc::new(MinuteFunction));
    registry.register(Arc::new(ModFunction));
    registry.register(Arc::new(ModeFunction));
    registry.register(Arc::new(MonthFunction));
    registry.register(Arc::new(NFunction));
    registry.register(Arc::new(NotFunction));
    registry.register(Arc::new(NowFunction));
    registry.register(Arc::new(OddFunction));
    registry.register(Arc::new(OrFunction));
    registry.register(Arc::new(PiFunction));
    registry.register(Arc::new(PowerFunction));
    registry.register(Arc::new(ProperFunction));
    registry.register(Arc::new(RadiansFunction));
    registry.register(Arc::new(RandFunction));
    registry.register(Arc::new(RandbetweenFunction));
    registry.register(Arc::new(ReplaceFunction));
    registry.register(Arc::new(RightFunction));
    registry.register(Arc::new(RoundFunction));
    registry.register(Arc::new(RounddownFunction));
    registry.register(Arc::new(RoundupFunction));
    registry.register(Arc::new(SearchFunction));
    registry.register(Arc::new(SecondFunction));
    registry.register(Arc::new(SignFunction));
    registry.register(Arc::new(SinFunction));
    registry.register(Arc::new(SinhFunction));
    registry.register(Arc::new(SqrtFunction));
    registry.register(Arc::new(StdevFunction));
    registry.register(Arc::new(StdevpFunction));
    registry.register(Arc::new(SubstituteFunction));
    registry.register(Arc::new(TanFunction));
    registry.register(Arc::new(TanhFunction));
    registry.register(Arc::new(TextFunction));
    registry.register(Arc::new(TimeFunction));
    registry.register(Arc::new(TimevalueFunction));
    registry.register(Arc::new(TodayFunction));
    registry.register(Arc::new(TrimFunction));
    registry.register(Arc::new(TrueFunction));
    registry.register(Arc::new(TruncFunction));
    registry.register(Arc::new(TypeFunction));
    registry.register(Arc::new(UpperFunction));
    registry.register(Arc::new(ValueFunction));
    registry.register(Arc::new(VarFunction));
    registry.register(Arc::new(VarpFunction));
    registry.register(Arc::new(VlookupFunction));
    registry.register(Arc::new(XorFunction));
    registry.register(Arc::new(YearFunction));
}

// Generated 103 function stubs
